### ISSUE TITLE
Thoughts on how to move forward with this

### ISSUE THREAD

**Issue by jsaddiction** [Nottt/scripts#1]
I see what you are doing with your code and think you may be better served using python.  I understand the limitations requiring your users to install python but the organization and available packages could help greatly.  Here is my concept:

Have one script that loads other modules based on a settings file to handle each implemented function.  

We could create one module that handles all subs in a more molecular way such as reading each file contained in the directory to determine language and validity of the file.  Once the "details" of the file are identified we could store that info in a dictionary.  Once all files are processed we handle the dictionary.  Loop through the dictionary to identify unwanted subs and identify subs that we want but don't have and download those.

Another module could handle artwork in very much the same way as the subs.

Another module could handle NFO creation.  I say creation because each release authority compiles their NFOs differently.  We could cultivate any info from their file, download missing data, then compile a version that is compatible with most media players.

I am not particularly good with bash scripting but google/trial and error could help me along if you would like to continue using this script.

**Comment by Nottt** [comment]
I have 0 knowledge in python :(

Seems the linuxserver deluge docker has `Python 2.7.13` so if you want to make a python version sure but I can't help it.

About the artworks, how many files are there normally and how are they named? NFO files can just be moved and renamed with bash just fine, I don't use NFOs at all so I think creating a NFO file is just increasing the complexity for almost no benefit...

**Comment by Nottt** [comment]
My quick attempt to deal with NFO and png/jpg files would be thi

```
if [ -z $NFO ]; then :
else mv "$SOURCEPATH"/*.nfo "$DESTINATION/${MOVIENAME%.*}.nfo" fi


if [ -z $ARTWORK ]; then :
else mv "$SOURCEPATH"/*.jpg "$DESTINATION/${MOVIENAME%.*}.jpg" 
     mv "$SOURCEPATH"/*.png "$DESTINATION/${MOVIENAME%.*}.png" fi
```

I still have to test it, but should work? Then when you go add the script in radarr, you can choose to pass the argument NFO and ARTWORK, if you do, they'll be moved. If you don't it will do nothing. 

Also about creating NFO files, you gotta think in what you want in them. Bit rate, resolution, release group? This can all be done using radarr environments and if necessary supplement with bit rate. That would be a lot of string parsing and manipulation that isn't really my strong area. But seems doable. 

Does artwork generally has more than one jpg/png file for the same movie? I just never use them so I have no idea at all. Maybe you can share some of your current files and structure ?

Also are you on radarr discord? Ping me there.
